New: Switch to MaxMind GeoLite2

diff --git a/geo-ip-block b/geo-ip-block
--- a/geo-ip-block
+++ b/geo-ip-block
@@ -6,21 +6,63 @@ function abort {
 }
 
 function download {
-  if [ -f /usr/bin/wget ]
+
+  [ -f "${0}.key" ] ||
+    abort "Missing license file ${0}.key"
+
+  local key="$(cat ${0}.key)"
+  local url="https://download.maxmind.com/geoip/databases/GeoLite2-Country-CSV/download?suffix=zip"
+  local out="GeoLite2-Country-CSV.zip"
+
+  if [ -f "${out}" ]
   then
-    wget -q -U geo-ip-block -O "/tmp/geo-ip-block/${1}" "${2}" ||
-      rm "/tmp/geo-ip-block/${1}"
-  else
-    curl -s -A geo-ip-block -o "/tmp/geo-ip-block/${1}" "${2}" ||
-      rm "/tmp/geo-ip-block/${1}"
+    local now=$(date +%s)
+    local age=$(stat -c %Y ${out})
+    age=$((${now} - ${age}))
+
+    if [ ${age} -lt 86400 ]
+    then
+      echo "✅ Up to date ${out}"
+      return
+    fi
   fi
 
-  echo "✅ Downloaded ${1}"
+  rm -rf "${out}"
+
+  curl -fs -JLA geo-ip-block -u "${key}" -o "${out}" "${url}" ||
+    abort "Failed downloading ${out}"
+  echo "✅ Downloaded ${out}"
+
+  rm -rf db
+  unzip -qjd db "${out}"
+  echo "✅ Extracted ${out}"
+}
+
+function build-ip-block-list {
+  local codes=$(echo "$@" | sed "s/ /|/g")
+  sed \
+    -nE "s/([0-9]+),.*,(${codes}),.*/\1/Ip" \
+    "db/GeoLite2-Country-Locations-en.csv" \
+    > "db/geoname_id"
+
+  local geoids="$(cat db/geoname_id)"
+  geoids=$(echo ${geoids} | sed "s/ /|/g")
+  echo ${geoids}
+
+  sed \
+    -nE "s/^([0-9:\.\/]+),(${geoids}),.*/\1/Ip" \
+    "db/GeoLite2-Country-Blocks-IPv4.csv" \
+    > "db/zone-ip4"
+
+  sed \
+    -nE "s/^([0-9:\.\/]+),(${geoids}),.*/\1/Ip" \
+    "db/GeoLite2-Country-Blocks-IPv6.csv" \
+    > "db/zone-ip6"
 }
 
 function delete-ipsets {
 
-  if ! firewall-cmd --info-ipset="geo-ip-block-list-${1}" &> /dev/null
+  if ! firewall-cmd --permanent --info-ipset="geo-ip-block-list-${1}" &> /dev/null
   then
     return
   fi
@@ -41,16 +83,13 @@ function delete-ipsets {
 }
 
 function load-entries {
-  for f in /tmp/geo-ip-block/*-${1}.zone
-  do
-    firewall-cmd \
-      --permanent \
-      --ipset="geo-ip-block-list-${1}" \
-      --add-entries-from-file="${f}" > /dev/null ||
-      abort "Failed loading ${f}"
+  firewall-cmd \
+    --permanent \
+    --ipset="geo-ip-block-list-${1}" \
+    --add-entries-from-file="db/zone-${1}" > /dev/null ||
+    abort "Failed loading ${f}"
 
-    echo "✅ Loaded ${f}"
-  done
+  echo "✅ Loaded ${f}"
 
   firewall-cmd \
     --permanent \
@@ -93,18 +132,13 @@ exec > >(tee "${log}") 2>&1
 banner
 echo -e "Execution time: $(date -Isec)"
 
-rm -rf /tmp/geo-ip-block &&
-mkdir -p /tmp/geo-ip-block ||
-  abort "Cannot write to /tmp/geo-ip-block"
+pushd $(dirname ${0}) &> /dev/null
 
-for z in ${ZONES}
-do
-  download $z-ip4.zone "https://www.ipdeny.com/ipblocks/data/aggregated/$z-aggregated.zone"
-  download $z-ip6.zone "https://www.ipdeny.com/ipv6/ipaddresses/aggregated/$z-aggregated.zone"
-done
+download
+build-ip-block-list ${ZONES}
 
-delete-ipsets "ip4"
-delete-ipsets "ip6"
+delete-ipsets ip4
+delete-ipsets ip6
 
 firewall-cmd \
   --permanent \
@@ -129,7 +163,7 @@ firewall-cmd \
 echo "✅ Created geo-ip-block-list-ip6"
 
 load-entries ip4
-load-entries ip6
+#load-entries ip6
 
 firewall-cmd --reload > /dev/null ||
   abort "Failed reloading firewall"
